### ISSUE TITLE
No me genera nodos, plugin recién instalado

### ISSUE THREAD

**Issue by axk2** [florantara/gatsby-source-mercadolibre#2]
cuando ejecuto gatsby develop me da el siguiente error

warn There was a problem with gatsby-source-mercadolibre. Check this endpoint: ↳ https://api.mercadolibre.com/sites/MLA/search?nickname=FRAVEGA
TypeError: Cannot read property 'length' of undefined
    at C:\Users\Luis\Desktop\agencia\mercadoback\node_modules\gatsby-source-mercadolibre\gatsby-node.js:59:66
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 20)
    at runAPI (C:\Users\Luis\Desktop\agencia\mercadoback\node_modules\gatsby\src\utils\api-runner-node.js:485:16)
warn The gatsby-source-mercadolibre plugin has generated no Gatsby nodes. Do you need it?

me dice que hay un problema con el endpoint que genera gatsby node, y que no genera nodos, entonces cuando lo busco en http://localhost:8000/___graphql no me arroja resultados

y tambien dice que los problemas pueden estar en las lineas 59 y 97 del plugin

yo revise el endpoint
https://api.mercadolibre.com/sites/MLA/search?nickname=FRAVEGA
y entrega bien la respuesta, con su "paging" "total", no se que puede estar fallando la verdad

en mi gatsby config
...
{
  resolve: `gatsby-source-mercadolibre`,
  options: {
    site_id: `MLA`,
    username: `FRAVEGA`
  }
},
....

no he hecho nada mas, estaba recien probando el plugin y me arrojó eso, aparte, probe eliminando la cache y todo.

**Comment by florantara** [comment]
@axk2 lo estaré mirando pronto, gracias por reportarlo
